export const BASE_BACKPACKS = [
  {
    "id": "Base_01",
    "isBase": true,
    "model": "Classic Daypack",
    "audience": "Woman",
    "purpose": "Travel",
    "material": "Polyester",
    "color": "Navy",
    "priceBand": "€50–€79",
    "price": 72,
    "imageUrl": "/backpacks/Base_01.jpg",
    "description": "Classic rounded daypack, front pocket, everyday travel/school."
  },
  {
    "id": "Base_02",
    "isBase": true,
    "model": "Kids Colorblock Backpack",
    "audience": "Child",
    "purpose": "Sports",
    "material": "Nylon",
    "color": "Teal/Yellow",
    "priceBand": "€0–€49",
    "price": 45,
    "imageUrl": "/backpacks/Base_02.jpg",
    "description": "Small kids backpack, bright colorblock, lightweight for activities."
  },
  {
    "id": "Base_03",
    "isBase": true,
    "model": "Slim Laptop Sleeve Pack",
    "audience": "Unisex",
    "purpose": "Business",
    "material": "Polyester",
    "color": "Matte Black",
    "priceBand": "€120–€179",
    "price": 129,
    "imageUrl": "/backpacks/Base_03.jpg",
    "description": "Minimal slim laptop backpack, clean rectangular silhouette."
  },
  {
    "id": "Base_04",
    "isBase": true,
    "model": "Business Commuter Backpack",
    "audience": "Man",
    "purpose": "Business",
    "material": "Polyester",
    "color": "Black",
    "priceBand": "€120–€179",
    "price": 149,
    "imageUrl": "/backpacks/Base_04.jpg",
    "description": "Structured office backpack, hidden zips, professional look."
  },
  {
    "id": "Base_05",
    "isBase": true,
    "model": "Minimal Rolltop Waterproof",
    "audience": "Unisex",
    "purpose": "Travel",
    "material": "Ripstop",
    "color": "Black",
    "priceBand": "€120–€179",
    "price": 139,
    "imageUrl": "/backpacks/Base_05.jpg",
    "description": "Rolltop backpack, waterproof vibe, simple front zip."
  },
  {
    "id": "Base_06",
    "isBase": true,
    "model": "Tactical Work Backpack",
    "audience": "Man",
    "purpose": "Mechanical work",
    "material": "Ripstop",
    "color": "Black",
    "priceBand": "€80–€119",
    "price": 112,
    "imageUrl": "/backpacks/Base_06.jpg",
    "description": "Rugged multi-pocket backpack for tools and heavy duty use."
  },
  {
    "id": "Base_07",
    "isBase": true,
    "model": "Sports Training Backpack",
    "audience": "Man",
    "purpose": "Sports",
    "material": "Polyester",
    "color": "Black",
    "priceBand": "€50–€79",
    "price": 73,
    "imageUrl": "/backpacks/Base_07.jpg",
    "description": "Sporty backpack with extra compartments and breathable straps."
  },
  {
    "id": "Base_08",
    "isBase": true,
    "model": "Hiking Trek Pack",
    "audience": "Man",
    "purpose": "Hiking",
    "material": "Ripstop",
    "color": "Charcoal",
    "priceBand": "€120–€179",
    "price": 159,
    "imageUrl": "/backpacks/Base_08.jpg",
    "description": "Large hiking backpack with compression straps and bungee cord."
  },
  {
    "id": "Base_09",
    "isBase": true,
    "model": "Canvas Rucksack",
    "audience": "Woman",
    "purpose": "Travel",
    "material": "Canvas",
    "color": "Tan",
    "priceBand": "€80–€119",
    "price": 101,
    "imageUrl": "/backpacks/Base_09.jpg",
    "description": "Vintage canvas rucksack with flap and strap details."
  },
  {
    "id": "Base_10",
    "isBase": true,
    "model": "Drawstring Gym Sack",
    "audience": "Unisex",
    "purpose": "Sports",
    "material": "Nylon",
    "color": "Navy",
    "priceBand": "€0–€49",
    "price": 19,
    "imageUrl": "/backpacks/Base_10.jpg",
    "description": "Light drawstring bag for gym / quick carry."
  },
  {
    "id": "Base_11",
    "isBase": true,
    "model": "Women City Daypack",
    "audience": "Woman",
    "purpose": "Travel",
    "material": "Polyester",
    "color": "Navy/Beige",
    "priceBand": "€50–€79",
    "price": 69,
    "imageUrl": "/backpacks/Base_11.jpg",
    "description": "Clean daypack with warm hardware accents, city use."
  },
  {
    "id": "Base_12",
    "isBase": true,
    "model": "Minimal Rolltop City",
    "audience": "Woman",
    "purpose": "Business",
    "material": "Cotton",
    "color": "Beige",
    "priceBand": "€80–€119",
    "price": 109,
    "imageUrl": "/backpacks/Base_12.jpg",
    "description": "Minimal rolltop, soft cotton/canvas look for office commute."
  },
  {
    "id": "Base_13",
    "isBase": true,
    "model": "Outdoor Expedition Pack",
    "audience": "Man",
    "purpose": "Hiking",
    "material": "Ripstop",
    "color": "Olive",
    "priceBand": "€120–€179",
    "price": 165,
    "imageUrl": "/backpacks/Base_13.jpg",
    "description": "Outdoor pack with big front pocket and bungee lacing."
  },
  {
    "id": "Base_14",
    "isBase": true,
    "model": "Slim Office Backpack",
    "audience": "Man",
    "purpose": "Business",
    "material": "Polyester",
    "color": "Navy",
    "priceBand": "€120–€179",
    "price": 129,
    "imageUrl": "/backpacks/Base_14.jpg",
    "description": "Slim business backpack, understated and structured."
  },
  {
    "id": "Base_15",
    "isBase": true,
    "model": "Kids Sports Backpack",
    "audience": "Child",
    "purpose": "Sports",
    "material": "Nylon",
    "color": "Bright Blue",
    "priceBand": "€0–€49",
    "price": 35,
    "imageUrl": "/backpacks/Base_15.jpg",
    "description": "Small kids sports backpack, playful and practical."
  },
  {
    "id": "Base_16",
    "isBase": true,
    "model": "Women’s Leather Work Backpack",
    "audience": "Woman",
    "purpose": "Work / Laptop",
    "material": "Leather",
    "color": "Cold Grey-Blue",
    "priceBand": "€120+",
    "price": 200,
    "imageUrl": "/backpacks/Base_16.jpg",
    "description": "Elegant women’s leather work backpack with a refined grey-blue tone, designed for office use and calm walks after work."
  },
  {
    "id": "Base_17",
    "isBase": true,
    "model": "Rainbow Unicorn Kindergarten Backpack",
    "audience": "Child",
    "purpose": "Kindergarten",
    "material": "Polyester / Cotton back",
    "color": "Sparkly Pink with Rainbow Unicorn",
    "priceBand": "€50–€79",
    "price": 75,
    "imageUrl": "/backpacks/Base_17.jpg",
    "description": "Small kindergarten backpack for ages 3–5 with a cute rainbow unicorn design. Lightweight, playful, and comfortable, with soft padded straps and child-friendly proportions."
  },
  {
    "id": "Base_18",
    "isBase": true,
    "model": "Pixel Hunter Backpack",
    "audience": "Child",
    "purpose": "School",
    "material": "Polyester",
    "color": "Dark Green",
    "priceBand": "€50–€79",
    "price": 75,
    "imageUrl": "/backpacks/Base_18.jpg",
    "description": "Children’s backpack for ages 7–9 inspired by pixel-style adventure games. Slightly larger to fit an iPad, with a friendly hunter character, sturdy construction, and padded straps for everyday school use."
  },
  {
    "id": "Var_18_1",
    "isBase": false,
    "name": "Pixel Magical Hero (Base 18)",
    "model": "Pixel Magical Hero Backpack",
    "audience": "Child",
    "purpose": "School",
    "material": "Polyester",
    "color": "Dark Green",
    "priceBand": "€50–€79",
    "price": 75,
    "imageUrl": "/backpacks/Var_18_1.jpg",
    "baseId": "Base_18",
    "description": "Game-inspired backpack for kids aged 7–9 with a pixel-style magical hero character. Same shape as Base_18, visually distinct hero design."
  },

{
  "id": "Var_04_1",
  "isBase": false,
  "baseId": "Base_04",
  "name": "Elegant Sakura Quilted Backpack",
  "model": "Business Commuter Backpack",
  "audience": "Woman",
  "purpose": "Business",
  "material": "Synthetic leather",
  "color": "Sakura Pink / Grass Green",
  "priceBand": "€120–€179",
  "price": 159,
  "imageUrl": "/backpacks/Var_04_1.png",
  "description": "Elegant women’s business backpack in rich sakura pink with quilted diamond stitching, emerald-green accents, and refined slim straps. Premium, feminine, and office-ready."
}



];
